name 'bjc_ecom_proxy'
maintainer 'Nick Rycar'
maintainer_email 'nrycar@chef.io'
license 'All Rights Reserved'
description 'Installs/Configures bjc_ecom_proxy'
long_description 'Installs/Configures bjc_ecom_proxy'
version '0.1.0'
chef_version '>= 12.1' if respond_to?(:chef_version)
depends 'haproxy'
issues_url 'https://github.com/ChefRycar/bjc_ecom_proxy/issues'
source_url 'https://github.com/ChefRycar/bjc_ecom_proxy'
